name: Deploy to Contabo

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Contabo
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GIT_REPO: ${{ github.repositoryUrl }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            # Update package lists
            apt-get update -y &&

            # Install Node.js and npm if not installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&
              apt-get install -y nodejs git
            fi &&

            # Install global dependencies
            npm install -g pm2 &&

            # Navigate to project directory
            mkdir -p /var/www &&
            cd /var/www &&

            # Clone repository if it doesn't exist
            if [ ! -d pet-speak ]; then
              git clone $GIT_REPO pet-speak &&
              cd pet-speak
            else
              cd pet-speak &&
              git pull origin master
            fi &&

            # Install dependencies
            npm install &&

            # Build the NestJS app
            npm run build || { echo 'Build failed'; exit 1; } &&

            # List contents of the dist directory for verification
            ls -la dist &&

            # Restart the application
            pm2 restart pet-speak || pm2 start dist/main.js --name pet-speak --watch
          "
