name: Deploy to Contabo

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Contabo
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            # Update package lists
            apt-get update -y &&

            # Install Node.js 20.x and npm if not installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
              apt-get install -y nodejs git
            fi &&

            # Install global dependencies
            npm install -g pm2 &&

            # Navigate to project directory
            mkdir -p /root &&
            cd /root &&

            # Clone repository if it doesn't exist
            if [ ! -d pet-speak-backend ]; then
              git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/${GITHUB_REPOSITORY}.git pet-speak-backend &&
              cd pet-speak-backend
            else
              cd pet-speak-backend &&
              git pull https://$GIT_USERNAME:$GIT_PASSWORD@github.com/${GITHUB_REPOSITORY}.git master
            fi &&

            # Install dependencies
            npm install &&

            # Build the NestJS app
            npm run build || { echo 'Build failed'; exit 1; } &&

            # Restart the application
            pm2 delete pet-speak-backend || true
            pm2 start /root/pet-speak-backend/dist/main.js --name pet-speak-backend --watch -- --port 80
            pm2 save
          "
