name: Deploy NestJS to Contabo

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Contabo
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            # Update package lists
            apt-get update -y

            # Install Node.js 20.x if not installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
              apt-get install -y nodejs git
            fi

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Navigate to project directory
            mkdir -p /root
            cd /root

            # Clone or update repository
            if [ ! -d pet-speak-backend ]; then
              git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/${GITHUB_REPOSITORY}.git pet-speak-backend
              cd pet-speak-backend
            else
              cd pet-speak-backend
              git pull https://$GIT_USERNAME:$GIT_PASSWORD@github.com/${GITHUB_REPOSITORY}.git master
            fi

            # Install dependencies and build
            npm install
            npm run build

            # Restart NestJS on port 3000 (will be proxied through Nginx)
            pm2 delete pet-speak-backend || true
            pm2 start /root/pet-speak-backend/dist/main.js --name pet-speak-backend --watch -- --port 3000
            pm2 save

            # Configure Nginx for NestJS (primary route)
            echo 'server {
                listen 80;
                server_name _;

                location /api/nest {
                    proxy_pass http://127.0.0.1:3000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }

                location / {
                    proxy_pass http://127.0.0.1:3000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }' > /etc/nginx/sites-available/pet-speak

            # Enable Nginx config
            ln -sf /etc/nginx/sites-available/pet-speak /etc/nginx/sites-enabled/
            rm -f /etc/nginx/sites-enabled/default
            systemctl restart nginx
          "
